unstable_features = true

hard_tabs = true
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
struct_lit_single_line = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
where_single_line = true
chain_width = 80
